---
- name: Distribute and execute script and capture public_key value
  hosts: test-ex
  become: yes
  tasks:
    - name: Copy the script to the remote hosts
      copy:
        src: /path/to/your/script.sh
        dest: /tmp/script.sh
        mode: '0755'

    - name: Execute the script
      shell: /tmp/script.sh
      register: script_output

    - name: Show script output
      debug:
        msg: "{{ script_output.stdout }}"
    
    - name: Extract public_key value
      set_fact:
        public_key_value: "{{ script_output.stdout | regex_search('public_key=(.*)') | first }}"
    
    - name: Show extracted public_key value
      debug:
        msg: "The public_key value is: {{ public_key_value }}"

